<?php

/**
 * Source-of-truth for `scripts/generate_controllers.php`. Each entry maps a
 * route slug to controller metadata (model class, columns, fields, rules)
 * so the generator can stamp out a thin `BaseCrudController` subclass.
 *
 * Hand-edit when you want to add a new module or tweak which columns
 * appear on the index page.
 */

declare(strict_types=1);

/** Reused field-config helpers — keep close to the migration column types. */
$T = static fn (string $n, string $l, bool $req = false) => ['text', $n, $l, $req];
$TX = static fn (string $n, string $l, bool $req = false, int $rows = 3) => ['textarea', $n, $l, $req, $rows];
$N = static fn (string $n, string $l, bool $req = false) => ['number', $n, $l, $req];
$D = static fn (string $n, string $l, bool $req = false) => ['decimal', $n, $l, $req];
$DT = static fn (string $n, string $l, bool $req = false) => ['datetime', $n, $l, $req];
$DA = static fn (string $n, string $l, bool $req = false) => ['date', $n, $l, $req];
$S = static fn (string $n, string $l, string $opts, bool $req = false) => ['select', $n, $l, $req, $opts];
$EM = static fn (string $n, string $l, bool $req = false) => ['email', $n, $l, $req];
$PW = static fn (string $n, string $l, bool $req = false) => ['password', $n, $l, $req];
$CB = static fn (string $n, string $l) => ['checkbox', $n, $l];

return [
    /* =================================================================
     | Property / branch management
     *================================================================ */
    'apartment-profiles' => [
        'class' => 'ApartmentProfileController',
        'model' => 'ApartmentProfile',
        'singular' => 'Branch / Apartment',
        'plural' => 'Branches / Apartments',
        'with' => ['propertyOwner'],
        'searchable' => ['apartment_code', 'name', 'phone', 'email'],
        'columns' => [
            'id' => '#',
            'apartment_code' => 'Code',
            'name' => 'Name',
            'propertyOwner.name' => 'Owner',
            'phone' => 'Phone',
            'currency' => 'Currency',
            'status' => 'Status',
        ],
        'fields' => [
            $S('property_owner_id', 'Property Owner', 'PropertyOwner', false),
            $T('apartment_code', 'Code', true),
            $T('name', 'Name', true),
            $T('logo_path', 'Logo Path'),
            $TX('address', 'Address'),
            $T('phone', 'Phone'),
            $EM('email', 'Email'),
            $T('website', 'Website'),
            $T('tax_identification_number', 'Tax ID'),
            $T('business_license_number', 'Business Licence'),
            $T('currency', 'Currency'),
            $T('timezone', 'Timezone'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'property-owners' => [
        'class' => 'PropertyOwnerController',
        'model' => 'PropertyOwner',
        'singular' => 'Property Owner',
        'plural' => 'Property Owners',
        'searchable' => ['owner_code', 'name', 'phone', 'email'],
        'columns' => [
            'id' => '#',
            'owner_code' => 'Code',
            'name' => 'Name',
            'phone' => 'Phone',
            'email' => 'Email',
            'ownership_percentage' => 'Ownership %',
            'status' => 'Status',
        ],
        'fields' => [
            $T('owner_code', 'Code', true),
            $T('name', 'Name', true),
            $T('phone', 'Phone'),
            $EM('email', 'Email'),
            $TX('address', 'Address'),
            $D('ownership_percentage', 'Ownership %'),
            $T('bank_name', 'Bank Name'),
            $T('bank_account_name', 'Account Name'),
            $T('bank_account_number', 'Account Number'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'legal-documents' => [
        'class' => 'LegalDocumentController',
        'model' => 'LegalDocument',
        'singular' => 'Legal Document',
        'plural' => 'Legal Documents',
        'searchable' => ['document_code', 'title', 'license_or_reference_no'],
        'columns' => [
            'id' => '#',
            'document_code' => 'Code',
            'document_type' => 'Type',
            'title' => 'Title',
            'expiry_date' => 'Expiry',
            'status' => 'Status',
        ],
        'fields' => [
            $T('document_code', 'Code', true),
            $S('document_type', 'Type', "['business_license' => 'Business License', 'permit' => 'Permit', 'tax_certificate' => 'Tax Certificate', 'insurance' => 'Insurance', 'other' => 'Other']", true),
            $T('title', 'Title', true),
            $T('license_or_reference_no', 'Reference No'),
            $DA('issue_date', 'Issue Date'),
            $DA('expiry_date', 'Expiry Date'),
            $T('file_path', 'File Path'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    /* =================================================================
     | Organisation
     *================================================================ */
    'departments' => [
        'class' => 'DepartmentController',
        'model' => 'Department',
        'singular' => 'Department',
        'plural' => 'Departments',
        'searchable' => ['department_code', 'name'],
        'columns' => [
            'id' => '#',
            'department_code' => 'Code',
            'name' => 'Name',
            'description' => 'Description',
            'status' => 'Status',
        ],
        'fields' => [
            $T('department_code', 'Code', true),
            $T('name', 'Name', true),
            $TX('description', 'Description'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'staff' => [
        'class' => 'StaffController',
        'model' => 'Staff',
        'singular' => 'Staff',
        'plural' => 'Staff',
        'with' => ['department'],
        'searchable' => ['staff_code', 'full_name', 'phone', 'email'],
        'columns' => [
            'id' => '#',
            'staff_code' => 'Code',
            'full_name' => 'Name',
            'department.name' => 'Department',
            'position' => 'Position',
            'phone' => 'Phone',
            'employment_status' => 'Status',
        ],
        'fields' => [
            $S('department_id', 'Department', 'Department', true),
            $T('staff_code', 'Code', true),
            $T('full_name', 'Full Name', true),
            $T('position', 'Position'),
            $T('phone', 'Phone'),
            $EM('email', 'Email'),
            $TX('address', 'Address'),
            $DA('hire_date', 'Hire Date'),
            $D('basic_salary', 'Basic Salary'),
            $S('employment_status', 'Status', "['active' => 'Active', 'on_leave' => 'On Leave', 'terminated' => 'Terminated', 'resigned' => 'Resigned']"),
        ],
    ],

    /* =================================================================
     | Tenants
     *================================================================ */
    'tenants' => [
        'class' => 'TenantController',
        'model' => 'Tenant',
        'singular' => 'Tenant',
        'plural' => 'Tenants',
        'searchable' => ['tenant_code', 'full_name', 'phone', 'email', 'id_card_number'],
        'columns' => [
            'id' => '#',
            'tenant_code' => 'Code',
            'full_name' => 'Name',
            'phone' => 'Phone',
            'email' => 'Email',
            'occupation' => 'Occupation',
            'status' => 'Status',
        ],
        'fields' => [
            $T('tenant_code', 'Code', true),
            $T('full_name', 'Full Name', true),
            $S('gender', 'Gender', "['male' => 'Male', 'female' => 'Female', 'other' => 'Other']"),
            $DA('date_of_birth', 'Date of Birth'),
            $T('phone', 'Phone'),
            $EM('email', 'Email'),
            $TX('address', 'Address'),
            $T('occupation', 'Occupation'),
            $T('nationality', 'Nationality'),
            $T('id_card_number', 'ID Card #'),
            $T('passport_number', 'Passport #'),
            $T('photo_path', 'Photo Path'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'tenant-contacts' => [
        'class' => 'TenantContactController',
        'model' => 'TenantContact',
        'singular' => 'Tenant Contact',
        'plural' => 'Tenant Contacts',
        'with' => ['tenant'],
        'searchable' => ['name', 'phone', 'email'],
        'columns' => [
            'id' => '#',
            'tenant.full_name' => 'Tenant',
            'contact_type' => 'Type',
            'name' => 'Name',
            'phone' => 'Phone',
        ],
        'fields' => [
            $S('tenant_id', 'Tenant', 'Tenant', true),
            $S('contact_type', 'Type', "['emergency' => 'Emergency', 'guarantor' => 'Guarantor', 'family' => 'Family', 'other' => 'Other']"),
            $T('name', 'Name', true),
            $T('relationship', 'Relationship'),
            $T('phone', 'Phone'),
            $EM('email', 'Email'),
            $TX('address', 'Address'),
        ],
    ],

    'tenant-documents' => [
        'class' => 'TenantDocumentController',
        'model' => 'TenantDocument',
        'singular' => 'Tenant Document',
        'plural' => 'Tenant Documents',
        'with' => ['tenant'],
        'searchable' => ['document_code', 'title'],
        'columns' => [
            'id' => '#',
            'tenant.full_name' => 'Tenant',
            'document_type' => 'Type',
            'title' => 'Title',
            'expiry_date' => 'Expiry',
            'is_verified' => 'Verified',
        ],
        'fields' => [
            $S('tenant_id', 'Tenant', 'Tenant', true),
            $T('document_code', 'Code'),
            $S('document_type', 'Type', "['id_card' => 'ID Card', 'passport' => 'Passport', 'driver_license' => 'Driver License', 'other' => 'Other']"),
            $T('title', 'Title', true),
            $T('file_path', 'File Path'),
            $DA('issue_date', 'Issue Date'),
            $DA('expiry_date', 'Expiry Date'),
            $CB('is_verified', 'Verified'),
        ],
    ],

    /* =================================================================
     | Property hierarchy
     *================================================================ */
    'buildings' => [
        'class' => 'BuildingController',
        'model' => 'Building',
        'singular' => 'Building',
        'plural' => 'Buildings',
        'with' => ['manager'],
        'searchable' => ['building_code', 'name', 'location'],
        'columns' => [
            'id' => '#',
            'building_code' => 'Code',
            'name' => 'Name',
            'location' => 'Location',
            'total_floors' => 'Floors',
            'total_rooms' => 'Rooms',
            'status' => 'Status',
        ],
        'fields' => [
            $S('manager_staff_id', 'Manager', 'Staff', false),
            $T('building_code', 'Code', true),
            $T('name', 'Name', true),
            $TX('location', 'Location'),
            $N('total_floors', 'Total Floors'),
            $N('total_rooms', 'Total Rooms'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'floors' => [
        'class' => 'FloorController',
        'model' => 'Floor',
        'singular' => 'Floor',
        'plural' => 'Floors',
        'with' => ['building'],
        'searchable' => ['floor_code'],
        'columns' => [
            'id' => '#',
            'building.name' => 'Building',
            'floor_code' => 'Code',
            'floor_number' => 'Floor #',
            'room_count' => 'Rooms',
            'status' => 'Status',
        ],
        'fields' => [
            $S('building_id', 'Building', 'Building', true),
            $T('floor_code', 'Code', true),
            $N('floor_number', 'Floor Number', true),
            $N('room_count', 'Rooms'),
            $T('floor_map_path', 'Map Path'),
            $TX('notes', 'Notes'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'room-types' => [
        'class' => 'RoomTypeController',
        'model' => 'RoomType',
        'singular' => 'Room Type',
        'plural' => 'Room Types',
        'searchable' => ['type_code', 'name'],
        'columns' => [
            'id' => '#',
            'type_code' => 'Code',
            'name' => 'Name',
            'default_monthly_rent' => 'Monthly Rent',
            'default_deposit_amount' => 'Deposit',
            'default_capacity' => 'Capacity',
            'status' => 'Status',
        ],
        'fields' => [
            $T('type_code', 'Code', true),
            $T('name', 'Name', true),
            $TX('description', 'Description'),
            $D('default_monthly_rent', 'Default Monthly Rent'),
            $D('default_deposit_amount', 'Default Deposit'),
            $N('default_capacity', 'Default Capacity'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'facilities' => [
        'class' => 'FacilityController',
        'model' => 'Facility',
        'singular' => 'Facility',
        'plural' => 'Facilities',
        'searchable' => ['facility_code', 'name', 'category'],
        'columns' => [
            'id' => '#',
            'facility_code' => 'Code',
            'name' => 'Name',
            'category' => 'Category',
            'status' => 'Status',
        ],
        'fields' => [
            $T('facility_code', 'Code', true),
            $T('name', 'Name', true),
            $T('category', 'Category'),
            $TX('description', 'Description'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'rooms' => [
        'class' => 'RoomController',
        'model' => 'Room',
        'singular' => 'Room',
        'plural' => 'Rooms',
        'with' => ['building', 'floor', 'roomType'],
        'searchable' => ['room_code', 'room_number'],
        'columns' => [
            'id' => '#',
            'room_code' => 'Code',
            'room_number' => 'Number',
            'building.name' => 'Building',
            'floor.floor_number' => 'Floor',
            'roomType.name' => 'Type',
            'monthly_rent' => 'Rent',
            'status' => 'Status',
        ],
        'fields' => [
            $S('building_id', 'Building', 'Building', true),
            $S('floor_id', 'Floor', 'Floor', true),
            $S('room_type_id', 'Room Type', 'RoomType', true),
            $T('room_code', 'Code', true),
            $T('room_number', 'Number', true),
            $D('size_sqm', 'Size (m²)'),
            $N('capacity', 'Capacity'),
            $D('monthly_rent', 'Monthly Rent'),
            $D('deposit_amount', 'Deposit Amount'),
            $TX('description', 'Description'),
            $S('status', 'Status', "['available' => 'Available', 'occupied' => 'Occupied', 'reserved' => 'Reserved', 'maintenance' => 'Maintenance', 'inactive' => 'Inactive']"),
        ],
    ],

    /* =================================================================
     | Booking & Contracts
     *================================================================ */
    'reservations' => [
        'class' => 'ReservationController',
        'model' => 'Reservation',
        'singular' => 'Reservation',
        'plural' => 'Reservations',
        'with' => ['room', 'tenant'],
        'searchable' => ['reservation_no', 'customer_name', 'phone'],
        'columns' => [
            'id' => '#',
            'reservation_no' => 'No.',
            'room.room_code' => 'Room',
            'customer_name' => 'Customer',
            'phone' => 'Phone',
            'planned_move_in_date' => 'Planned Move-in',
            'deposit_amount' => 'Deposit',
            'status' => 'Status',
        ],
        'fields' => [
            $T('reservation_no', 'No.', true),
            $S('room_id', 'Room', 'Room', true),
            $S('tenant_id', 'Tenant', 'Tenant'),
            $T('customer_name', 'Customer'),
            $T('phone', 'Phone'),
            $EM('email', 'Email'),
            $DA('planned_move_in_date', 'Planned Move-in'),
            $D('deposit_amount', 'Deposit'),
            $DA('deposit_paid_date', 'Deposit Paid'),
            $TX('notes', 'Notes'),
            $S('status', 'Status', "['pending' => 'Pending', 'confirmed' => 'Confirmed', 'cancelled' => 'Cancelled', 'converted' => 'Converted']"),
        ],
    ],

    'rental-contracts' => [
        'class' => 'RentalContractController',
        'model' => 'RentalContract',
        'singular' => 'Rental Contract',
        'plural' => 'Rental Contracts',
        'with' => ['tenant', 'room'],
        'searchable' => ['contract_no'],
        'columns' => [
            'id' => '#',
            'contract_no' => 'No.',
            'tenant.full_name' => 'Tenant',
            'room.room_code' => 'Room',
            'start_date' => 'Start',
            'end_date' => 'End',
            'monthly_rent' => 'Monthly Rent',
            'status' => 'Status',
        ],
        'fields' => [
            $T('contract_no', 'No.', true),
            $S('tenant_id', 'Tenant', 'Tenant', true),
            $S('room_id', 'Room', 'Room', true),
            $S('reservation_id', 'Reservation', 'Reservation'),
            $DA('start_date', 'Start Date', true),
            $DA('end_date', 'End Date', true),
            $D('monthly_rent', 'Monthly Rent', true),
            $D('deposit_amount', 'Deposit'),
            $N('payment_due_day', 'Payment Due Day'),
            $TX('terms_conditions', 'Terms & Conditions', false, 6),
            $T('signed_contract_path', 'Signed Contract Path'),
            $DA('signed_date', 'Signed Date'),
            $S('status', 'Status', "['draft' => 'Draft', 'active' => 'Active', 'expired' => 'Expired', 'terminated' => 'Terminated']"),
        ],
    ],

    'contract-renewals' => [
        'class' => 'ContractRenewalController',
        'model' => 'ContractRenewal',
        'singular' => 'Contract Renewal',
        'plural' => 'Contract Renewals',
        'with' => ['contract'],
        'searchable' => ['renewal_no'],
        'columns' => [
            'id' => '#',
            'renewal_no' => 'No.',
            'contract.contract_no' => 'Contract',
            'new_start_date' => 'New Start',
            'new_end_date' => 'New End',
            'new_monthly_rent' => 'New Rent',
            'status' => 'Status',
        ],
        'fields' => [
            $T('renewal_no', 'No.', true),
            $S('contract_id', 'Contract', 'RentalContract', true),
            $DA('old_end_date', 'Old End Date'),
            $DA('new_start_date', 'New Start Date'),
            $DA('new_end_date', 'New End Date'),
            $D('old_monthly_rent', 'Old Rent'),
            $D('new_monthly_rent', 'New Rent'),
            $D('old_deposit_amount', 'Old Deposit'),
            $D('new_deposit_amount', 'New Deposit'),
            $T('renewal_document_path', 'Document Path'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'contract-terminations' => [
        'class' => 'ContractTerminationController',
        'model' => 'ContractTermination',
        'singular' => 'Contract Termination',
        'plural' => 'Contract Terminations',
        'with' => ['contract'],
        'searchable' => ['termination_no', 'reason'],
        'columns' => [
            'id' => '#',
            'termination_no' => 'No.',
            'contract.contract_no' => 'Contract',
            'termination_date' => 'Date',
            'outstanding_balance' => 'Outstanding',
            'deposit_refund' => 'Refund',
            'status' => 'Status',
        ],
        'fields' => [
            $T('termination_no', 'No.', true),
            $S('contract_id', 'Contract', 'RentalContract', true),
            $DA('termination_date', 'Termination Date'),
            $TX('reason', 'Reason'),
            $D('outstanding_balance', 'Outstanding Balance'),
            $D('deposit_deduction', 'Deposit Deduction'),
            $D('deposit_refund', 'Deposit Refund'),
            $T('termination_letter_path', 'Letter Path'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'move-in-records' => [
        'class' => 'MoveInRecordController',
        'model' => 'MoveInRecord',
        'singular' => 'Move-In Record',
        'plural' => 'Move-In Records',
        'with' => ['contract', 'tenant', 'room'],
        'searchable' => ['move_in_no'],
        'columns' => [
            'id' => '#',
            'move_in_no' => 'No.',
            'tenant.full_name' => 'Tenant',
            'room.room_code' => 'Room',
            'move_in_date' => 'Move-in Date',
            'status' => 'Status',
        ],
        'fields' => [
            $T('move_in_no', 'No.', true),
            $S('contract_id', 'Contract', 'RentalContract'),
            $S('tenant_id', 'Tenant', 'Tenant', true),
            $S('room_id', 'Room', 'Room', true),
            $DA('move_in_date', 'Date'),
            $TX('room_condition', 'Room Condition'),
            $TX('facility_condition', 'Facility Condition'),
            $D('water_meter_reading', 'Water Meter'),
            $D('electric_meter_reading', 'Electric Meter'),
            $T('tenant_signature_path', 'Signature'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'move-out-records' => [
        'class' => 'MoveOutRecordController',
        'model' => 'MoveOutRecord',
        'singular' => 'Move-Out Record',
        'plural' => 'Move-Out Records',
        'with' => ['contract', 'tenant', 'room'],
        'searchable' => ['move_out_no'],
        'columns' => [
            'id' => '#',
            'move_out_no' => 'No.',
            'tenant.full_name' => 'Tenant',
            'room.room_code' => 'Room',
            'move_out_date' => 'Move-out',
            'deposit_refund' => 'Refund',
            'status' => 'Status',
        ],
        'fields' => [
            $T('move_out_no', 'No.', true),
            $S('contract_id', 'Contract', 'RentalContract'),
            $S('tenant_id', 'Tenant', 'Tenant', true),
            $S('room_id', 'Room', 'Room', true),
            $DA('move_out_date', 'Date'),
            $TX('room_condition', 'Room Condition'),
            $TX('damaged_items', 'Damaged Items'),
            $D('final_water_meter_reading', 'Water Meter'),
            $D('final_electric_meter_reading', 'Electric Meter'),
            $D('outstanding_balance', 'Outstanding'),
            $D('damage_deduction', 'Damage Deduction'),
            $D('deposit_refund', 'Deposit Refund'),
            $T('tenant_signature_path', 'Signature'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    /* =================================================================
     | Utilities & Service fees
     *================================================================ */
    'utility-types' => [
        'class' => 'UtilityTypeController',
        'model' => 'UtilityType',
        'singular' => 'Utility Type',
        'plural' => 'Utility Types',
        'searchable' => ['utility_code', 'name'],
        'columns' => [
            'id' => '#',
            'utility_code' => 'Code',
            'name' => 'Name',
            'unit' => 'Unit',
            'billing_method' => 'Method',
            'status' => 'Status',
        ],
        'fields' => [
            $T('utility_code', 'Code', true),
            $T('name', 'Name', true),
            $T('unit', 'Unit'),
            $S('billing_method', 'Billing Method', "['metered' => 'Metered', 'flat' => 'Flat', 'tiered' => 'Tiered']"),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'utility-rates' => [
        'class' => 'UtilityRateController',
        'model' => 'UtilityRate',
        'singular' => 'Utility Rate',
        'plural' => 'Utility Rates',
        'with' => ['utilityType'],
        'searchable' => [],
        'columns' => [
            'id' => '#',
            'utilityType.name' => 'Utility',
            'price_per_unit' => 'Price/Unit',
            'minimum_charge' => 'Min Charge',
            'effective_from' => 'From',
            'effective_to' => 'To',
            'status' => 'Status',
        ],
        'fields' => [
            $S('utility_type_id', 'Utility Type', 'UtilityType', true),
            $D('price_per_unit', 'Price per Unit'),
            $D('minimum_charge', 'Minimum Charge'),
            $DA('effective_from', 'Effective From'),
            $DA('effective_to', 'Effective To'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'utility-meters' => [
        'class' => 'UtilityMeterController',
        'model' => 'UtilityMeter',
        'singular' => 'Utility Meter',
        'plural' => 'Utility Meters',
        'with' => ['room', 'utilityType'],
        'searchable' => ['meter_no'],
        'columns' => [
            'id' => '#',
            'meter_no' => 'Meter No.',
            'room.room_code' => 'Room',
            'utilityType.name' => 'Utility',
            'initial_reading' => 'Initial',
            'status' => 'Status',
        ],
        'fields' => [
            $S('room_id', 'Room', 'Room', true),
            $S('utility_type_id', 'Utility Type', 'UtilityType', true),
            $T('meter_no', 'Meter No.', true),
            $D('initial_reading', 'Initial Reading'),
            $DA('installed_date', 'Installed'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'utility-readings' => [
        'class' => 'UtilityReadingController',
        'model' => 'UtilityReading',
        'singular' => 'Utility Reading',
        'plural' => 'Utility Readings',
        'with' => ['room', 'meter'],
        'searchable' => ['reading_no', 'billing_month'],
        'columns' => [
            'id' => '#',
            'reading_no' => 'No.',
            'room.room_code' => 'Room',
            'billing_month' => 'Month',
            'old_reading' => 'Old',
            'new_reading' => 'New',
            'usage_unit' => 'Usage',
            'total_fee' => 'Total Fee',
            'status' => 'Status',
        ],
        'fields' => [
            $T('reading_no', 'No.', true),
            $S('utility_meter_id', 'Meter', 'UtilityMeter', true),
            $S('room_id', 'Room', 'Room'),
            $S('contract_id', 'Contract', 'RentalContract'),
            $DA('reading_date', 'Reading Date', true),
            $T('billing_month', 'Billing Month (YYYY-MM)'),
            $D('old_reading', 'Old Reading'),
            $D('new_reading', 'New Reading'),
            $D('usage_unit', 'Usage Unit'),
            $D('price_per_unit', 'Price/Unit'),
            $D('total_fee', 'Total Fee'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'service-fees' => [
        'class' => 'ServiceFeeController',
        'model' => 'ServiceFee',
        'singular' => 'Service Fee',
        'plural' => 'Service Fees',
        'searchable' => ['service_code', 'name'],
        'columns' => [
            'id' => '#',
            'service_code' => 'Code',
            'name' => 'Name',
            'fee_type' => 'Type',
            'amount' => 'Amount',
            'status' => 'Status',
        ],
        'fields' => [
            $T('service_code', 'Code', true),
            $T('name', 'Name', true),
            $S('fee_type', 'Type', "['monthly' => 'Monthly', 'one_time' => 'One-time', 'metered' => 'Metered']"),
            $D('amount', 'Amount'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    /* =================================================================
     | Billing
     *================================================================ */
    'invoices' => [
        'class' => 'InvoiceController',
        'model' => 'Invoice',
        'singular' => 'Invoice',
        'plural' => 'Invoices',
        'with' => ['tenant', 'room'],
        'searchable' => ['invoice_no', 'billing_month'],
        'columns' => [
            'id' => '#',
            'invoice_no' => 'No.',
            'tenant.full_name' => 'Tenant',
            'room.room_code' => 'Room',
            'billing_month' => 'Month',
            'grand_total' => 'Total',
            'paid_amount' => 'Paid',
            'balance_due' => 'Balance',
            'status' => 'Status',
        ],
        'fields' => [
            $T('invoice_no', 'No.', true),
            $S('tenant_id', 'Tenant', 'Tenant', true),
            $S('room_id', 'Room', 'Room'),
            $S('contract_id', 'Contract', 'RentalContract'),
            $T('billing_month', 'Month (YYYY-MM)'),
            $DA('invoice_date', 'Invoice Date', true),
            $DA('due_date', 'Due Date', true),
            $D('room_fee', 'Room Fee'),
            $D('water_fee', 'Water Fee'),
            $D('electricity_fee', 'Electricity Fee'),
            $D('service_fee', 'Service Fee'),
            $D('old_balance', 'Old Balance'),
            $D('discount', 'Discount'),
            $D('penalty', 'Penalty'),
            $D('subtotal', 'Subtotal'),
            $D('grand_total', 'Grand Total'),
            $D('paid_amount', 'Paid'),
            $D('balance_due', 'Balance Due'),
            $S('status', 'Status', "['draft' => 'Draft', 'issued' => 'Issued', 'paid' => 'Paid', 'partial' => 'Partial', 'overdue' => 'Overdue', 'cancelled' => 'Cancelled']"),
        ],
    ],

    'payments' => [
        'class' => 'PaymentController',
        'model' => 'Payment',
        'singular' => 'Payment',
        'plural' => 'Payments',
        'with' => ['tenant', 'invoice'],
        'searchable' => ['payment_no', 'transaction_reference'],
        'columns' => [
            'id' => '#',
            'payment_no' => 'No.',
            'tenant.full_name' => 'Tenant',
            'invoice.invoice_no' => 'Invoice',
            'amount_paid' => 'Amount',
            'payment_method' => 'Method',
            'payment_date' => 'Date',
            'status' => 'Status',
        ],
        'fields' => [
            $T('payment_no', 'No.', true),
            $S('tenant_id', 'Tenant', 'Tenant', true),
            $S('invoice_id', 'Invoice', 'Invoice'),
            $DA('payment_date', 'Date', true),
            $D('amount_paid', 'Amount', true),
            $S('payment_method', 'Method', "['cash' => 'Cash', 'bank_transfer' => 'Bank Transfer', 'credit_card' => 'Credit Card', 'aba_pay' => 'ABA Pay', 'wing' => 'Wing', 'other' => 'Other']"),
            $T('transaction_reference', 'Reference'),
            $T('slip_path', 'Slip Path'),
            $TX('notes', 'Notes'),
            $S('status', 'Status', "['pending' => 'Pending', 'completed' => 'Completed', 'failed' => 'Failed', 'cancelled' => 'Cancelled']"),
        ],
    ],

    'receipts' => [
        'class' => 'ReceiptController',
        'model' => 'Receipt',
        'singular' => 'Receipt',
        'plural' => 'Receipts',
        'with' => ['payment', 'invoice'],
        'searchable' => ['receipt_no'],
        'columns' => [
            'id' => '#',
            'receipt_no' => 'No.',
            'invoice.invoice_no' => 'Invoice',
            'amount_paid' => 'Paid',
            'balance_due' => 'Balance',
            'receipt_date' => 'Date',
            'status' => 'Status',
        ],
        'fields' => [
            $T('receipt_no', 'No.', true),
            $S('payment_id', 'Payment', 'Payment'),
            $S('invoice_id', 'Invoice', 'Invoice'),
            $D('amount_paid', 'Amount Paid'),
            $D('balance_due', 'Balance Due'),
            $DA('receipt_date', 'Date'),
            $T('received_by', 'Received By'),
            $T('pdf_path', 'PDF Path'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'penalty-rules' => [
        'class' => 'PenaltyRuleController',
        'model' => 'PenaltyRule',
        'singular' => 'Penalty Rule',
        'plural' => 'Penalty Rules',
        'searchable' => ['rule_code', 'name'],
        'columns' => [
            'id' => '#',
            'rule_code' => 'Code',
            'name' => 'Name',
            'penalty_type' => 'Type',
            'rate_or_amount' => 'Rate/Amount',
            'grace_days' => 'Grace Days',
            'status' => 'Status',
        ],
        'fields' => [
            $T('rule_code', 'Code', true),
            $T('name', 'Name', true),
            $S('penalty_type', 'Type', "['fixed' => 'Fixed Amount', 'percentage' => 'Percentage', 'daily' => 'Daily']"),
            $D('rate_or_amount', 'Rate / Amount'),
            $N('grace_days', 'Grace Days'),
            $D('maximum_penalty', 'Maximum Penalty'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'debt-reminders' => [
        'class' => 'DebtReminderController',
        'model' => 'DebtReminder',
        'singular' => 'Debt Reminder',
        'plural' => 'Debt Reminders',
        'with' => ['tenant', 'invoice'],
        'searchable' => ['reminder_no'],
        'columns' => [
            'id' => '#',
            'reminder_no' => 'No.',
            'tenant.full_name' => 'Tenant',
            'invoice.invoice_no' => 'Invoice',
            'reminder_channel' => 'Channel',
            'amount_due' => 'Due',
            'overdue_days' => 'Days Late',
            'delivery_status' => 'Status',
        ],
        'fields' => [
            $T('reminder_no', 'No.', true),
            $S('tenant_id', 'Tenant', 'Tenant', true),
            $S('invoice_id', 'Invoice', 'Invoice'),
            $S('reminder_channel', 'Channel', "['sms' => 'SMS', 'email' => 'Email', 'phone' => 'Phone', 'in_person' => 'In Person']"),
            $DA('reminder_date', 'Date'),
            $D('amount_due', 'Amount Due'),
            $N('overdue_days', 'Overdue Days'),
            $TX('message', 'Message'),
            $S('delivery_status', 'Delivery Status', "['pending' => 'Pending', 'sent' => 'Sent', 'failed' => 'Failed']"),
        ],
    ],

    /* =================================================================
     | Maintenance + Cleaning
     *================================================================ */
    'maintenance-requests' => [
        'class' => 'MaintenanceRequestController',
        'model' => 'MaintenanceRequest',
        'singular' => 'Maintenance Request',
        'plural' => 'Maintenance Requests',
        'with' => ['room', 'tenant', 'assignedStaff'],
        'searchable' => ['request_no', 'problem_type'],
        'columns' => [
            'id' => '#',
            'request_no' => 'No.',
            'room.room_code' => 'Room',
            'tenant.full_name' => 'Tenant',
            'problem_type' => 'Problem',
            'priority' => 'Priority',
            'total_cost' => 'Cost',
            'status' => 'Status',
        ],
        'fields' => [
            $T('request_no', 'No.', true),
            $S('room_id', 'Room', 'Room', true),
            $S('tenant_id', 'Tenant', 'Tenant'),
            $S('assigned_staff_id', 'Assigned Staff', 'Staff'),
            $T('problem_type', 'Problem Type'),
            $TX('description', 'Description'),
            $S('priority', 'Priority', "['low' => 'Low', 'medium' => 'Medium', 'high' => 'High', 'urgent' => 'Urgent']"),
            $D('material_cost', 'Material Cost'),
            $D('labor_cost', 'Labor Cost'),
            $D('service_cost', 'Service Cost'),
            $D('other_cost', 'Other Cost'),
            $D('total_cost', 'Total Cost'),
            $DT('requested_at', 'Requested At'),
            $DT('completed_at', 'Completed At'),
            $S('status', 'Status', "['pending' => 'Pending', 'in_progress' => 'In Progress', 'completed' => 'Completed', 'cancelled' => 'Cancelled']"),
        ],
    ],

    'preventive-maintenance-schedules' => [
        'class' => 'PreventiveMaintenanceScheduleController',
        'model' => 'PreventiveMaintenanceSchedule',
        'singular' => 'Preventive Maintenance',
        'plural' => 'Preventive Maintenance',
        'searchable' => ['schedule_no', 'maintenance_type'],
        'columns' => [
            'id' => '#',
            'schedule_no' => 'No.',
            'maintenance_type' => 'Type',
            'scheduled_date' => 'Scheduled',
            'completed_date' => 'Completed',
            'status' => 'Status',
        ],
        'fields' => [
            $T('schedule_no', 'No.', true),
            $S('building_id', 'Building', 'Building'),
            $S('room_id', 'Room', 'Room'),
            $S('assigned_staff_id', 'Assigned Staff', 'Staff'),
            $T('maintenance_type', 'Type'),
            $DA('scheduled_date', 'Scheduled Date'),
            $DA('completed_date', 'Completed Date'),
            $TX('checklist', 'Checklist', false, 4),
            $TX('result_notes', 'Result Notes', false, 3),
            $S('status', 'Status', "['scheduled' => 'Scheduled', 'in_progress' => 'In Progress', 'completed' => 'Completed', 'cancelled' => 'Cancelled']"),
        ],
    ],

    'cleaning-tasks' => [
        'class' => 'CleaningTaskController',
        'model' => 'CleaningTask',
        'singular' => 'Cleaning Task',
        'plural' => 'Cleaning Tasks',
        'searchable' => ['task_no', 'area_type'],
        'columns' => [
            'id' => '#',
            'task_no' => 'No.',
            'area_type' => 'Area',
            'cleaning_date' => 'Date',
            'status' => 'Status',
        ],
        'fields' => [
            $T('task_no', 'No.', true),
            $S('room_id', 'Room', 'Room'),
            $S('building_id', 'Building', 'Building'),
            $S('assigned_staff_id', 'Assigned Staff', 'Staff'),
            $S('area_type', 'Area Type', "['room' => 'Room', 'common' => 'Common Area', 'building' => 'Whole Building']"),
            $T('public_area', 'Public Area'),
            $DA('cleaning_date', 'Cleaning Date'),
            $TX('remark', 'Remark'),
            $S('status', 'Status', "['pending' => 'Pending', 'in_progress' => 'In Progress', 'completed' => 'Completed']"),
        ],
    ],

    /* =================================================================
     | Inventory + Procurement
     *================================================================ */
    'inventory-categories' => [
        'class' => 'InventoryCategoryController',
        'model' => 'InventoryCategory',
        'singular' => 'Inventory Category',
        'plural' => 'Inventory Categories',
        'searchable' => ['category_code', 'name'],
        'columns' => [
            'id' => '#',
            'category_code' => 'Code',
            'name' => 'Name',
            'description' => 'Description',
            'status' => 'Status',
        ],
        'fields' => [
            $T('category_code', 'Code', true),
            $T('name', 'Name', true),
            $TX('description', 'Description'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'suppliers' => [
        'class' => 'SupplierController',
        'model' => 'Supplier',
        'singular' => 'Supplier',
        'plural' => 'Suppliers',
        'searchable' => ['supplier_code', 'supplier_name', 'phone', 'email'],
        'columns' => [
            'id' => '#',
            'supplier_code' => 'Code',
            'supplier_name' => 'Name',
            'phone' => 'Phone',
            'rating' => 'Rating',
            'status' => 'Status',
        ],
        'fields' => [
            $T('supplier_code', 'Code', true),
            $T('supplier_name', 'Name', true),
            $T('phone', 'Phone'),
            $EM('email', 'Email'),
            $TX('address', 'Address'),
            $T('contact_person', 'Contact Person'),
            $T('payment_term', 'Payment Term'),
            $D('rating', 'Rating'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'inventory-items' => [
        'class' => 'InventoryItemController',
        'model' => 'InventoryItem',
        'singular' => 'Inventory Item',
        'plural' => 'Inventory Items',
        'with' => ['category', 'supplier'],
        'searchable' => ['item_code', 'item_name'],
        'columns' => [
            'id' => '#',
            'item_code' => 'Code',
            'item_name' => 'Name',
            'category.name' => 'Category',
            'supplier.supplier_name' => 'Supplier',
            'unit' => 'Unit',
            'current_stock' => 'Stock',
            'status' => 'Status',
        ],
        'fields' => [
            $S('inventory_category_id', 'Category', 'InventoryCategory', true),
            $S('supplier_id', 'Supplier', 'Supplier'),
            $T('item_code', 'Code', true),
            $T('item_name', 'Name', true),
            $T('unit', 'Unit'),
            $D('purchase_price', 'Purchase Price'),
            $D('current_stock', 'Current Stock'),
            $D('minimum_stock', 'Minimum Stock'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'purchase-orders' => [
        'class' => 'PurchaseOrderController',
        'model' => 'PurchaseOrder',
        'singular' => 'Purchase Order',
        'plural' => 'Purchase Orders',
        'with' => ['supplier'],
        'searchable' => ['po_no'],
        'columns' => [
            'id' => '#',
            'po_no' => 'No.',
            'supplier.supplier_name' => 'Supplier',
            'po_date' => 'Date',
            'total_amount' => 'Total',
            'status' => 'Status',
        ],
        'fields' => [
            $T('po_no', 'No.', true),
            $S('supplier_id', 'Supplier', 'Supplier', true),
            $DA('po_date', 'Order Date'),
            $DA('expected_delivery_date', 'Expected Delivery'),
            $D('total_amount', 'Total Amount'),
            $S('status', 'Status', "['draft' => 'Draft', 'pending' => 'Pending', 'approved' => 'Approved', 'received' => 'Received', 'cancelled' => 'Cancelled']"),
        ],
    ],

    'goods-receipts' => [
        'class' => 'GoodsReceiptController',
        'model' => 'GoodsReceipt',
        'singular' => 'Goods Receipt',
        'plural' => 'Goods Receipts',
        'searchable' => ['grn_no'],
        'columns' => [
            'id' => '#',
            'grn_no' => 'GRN No.',
            'received_date' => 'Date',
            'status' => 'Status',
        ],
        'fields' => [
            $T('grn_no', 'GRN No.', true),
            $S('purchase_order_id', 'Purchase Order', 'PurchaseOrder'),
            $DA('received_date', 'Received Date'),
            $T('received_by', 'Received By'),
            $TX('notes', 'Notes'),
            $S('status', 'Status', "['received' => 'Received', 'partial' => 'Partial', 'rejected' => 'Rejected']"),
        ],
    ],

    'stock-movements' => [
        'class' => 'StockMovementController',
        'model' => 'StockMovement',
        'singular' => 'Stock Movement',
        'plural' => 'Stock Movements',
        'searchable' => ['movement_no'],
        'columns' => [
            'id' => '#',
            'movement_no' => 'No.',
            'movement_type' => 'Type',
            'quantity' => 'Qty',
            'movement_date' => 'Date',
        ],
        'fields' => [
            $T('movement_no', 'No.', true),
            $S('inventory_item_id', 'Item', 'InventoryItem', true),
            $S('movement_type', 'Type', "['in' => 'In', 'out' => 'Out', 'adjustment' => 'Adjustment', 'transfer' => 'Transfer']"),
            $D('quantity', 'Quantity'),
            $D('unit_cost', 'Unit Cost'),
            $D('total_cost', 'Total Cost'),
            $T('reference_type', 'Reference Type'),
            $N('reference_id', 'Reference ID'),
            $DA('movement_date', 'Date'),
            $T('performed_by', 'Performed By'),
            $TX('notes', 'Notes'),
        ],
    ],

    'assets' => [
        'class' => 'AssetController',
        'model' => 'Asset',
        'singular' => 'Asset',
        'plural' => 'Assets',
        'searchable' => ['asset_code', 'asset_name'],
        'columns' => [
            'id' => '#',
            'asset_code' => 'Code',
            'asset_name' => 'Name',
            'purchase_date' => 'Purchased',
            'purchase_price' => 'Price',
            'condition' => 'Condition',
            'status' => 'Status',
        ],
        'fields' => [
            $T('asset_code', 'Code', true),
            $T('asset_name', 'Name', true),
            $S('room_id', 'Room', 'Room'),
            $S('inventory_item_id', 'Item', 'InventoryItem'),
            $DA('purchase_date', 'Purchase Date'),
            $D('purchase_price', 'Purchase Price'),
            $S('condition', 'Condition', "['new' => 'New', 'good' => 'Good', 'fair' => 'Fair', 'damaged' => 'Damaged']"),
            $DA('warranty_expiry_date', 'Warranty Expiry'),
            $D('depreciation_rate', 'Depreciation Rate'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    /* =================================================================
     | HR
     *================================================================ */
    'staff-attendances' => [
        'class' => 'StaffAttendanceController',
        'model' => 'StaffAttendance',
        'singular' => 'Staff Attendance',
        'plural' => 'Staff Attendance',
        'searchable' => [],
        'columns' => [
            'id' => '#',
            'staff_id' => 'Staff',
            'attendance_date' => 'Date',
            'time_in' => 'In',
            'time_out' => 'Out',
            'attendance_status' => 'Status',
        ],
        'fields' => [
            $S('staff_id', 'Staff', 'Staff', true),
            $DA('attendance_date', 'Date'),
            $T('time_in', 'Time In'),
            $T('time_out', 'Time Out'),
            $N('late_minutes', 'Late (min)'),
            $N('early_leave_minutes', 'Early Leave (min)'),
            $S('attendance_status', 'Status', "['present' => 'Present', 'absent' => 'Absent', 'leave' => 'Leave', 'late' => 'Late', 'half_day' => 'Half Day']"),
            $TX('notes', 'Notes'),
        ],
    ],

    'payrolls' => [
        'class' => 'PayrollController',
        'model' => 'Payroll',
        'singular' => 'Payroll',
        'plural' => 'Payrolls',
        'searchable' => ['payroll_no', 'payroll_month'],
        'columns' => [
            'id' => '#',
            'payroll_no' => 'No.',
            'payroll_month' => 'Month',
            'net_salary' => 'Net Salary',
            'paid_date' => 'Paid On',
            'status' => 'Status',
        ],
        'fields' => [
            $T('payroll_no', 'No.', true),
            $S('staff_id', 'Staff', 'Staff', true),
            $T('payroll_month', 'Month (YYYY-MM)'),
            $D('basic_salary', 'Basic Salary'),
            $D('overtime_amount', 'Overtime'),
            $D('allowance_amount', 'Allowance'),
            $D('deduction_amount', 'Deduction'),
            $D('bonus_amount', 'Bonus'),
            $D('net_salary', 'Net Salary'),
            $DA('paid_date', 'Paid Date'),
            $S('status', 'Status', "['draft' => 'Draft', 'approved' => 'Approved', 'paid' => 'Paid']"),
        ],
    ],

    'staff-documents' => [
        'class' => 'StaffDocumentController',
        'model' => 'StaffDocument',
        'singular' => 'Staff Document',
        'plural' => 'Staff Documents',
        'searchable' => ['document_code', 'title'],
        'columns' => [
            'id' => '#',
            'document_code' => 'Code',
            'document_type' => 'Type',
            'title' => 'Title',
            'expiry_date' => 'Expiry',
        ],
        'fields' => [
            $S('staff_id', 'Staff', 'Staff', true),
            $T('document_code', 'Code'),
            $T('document_type', 'Type'),
            $T('title', 'Title', true),
            $T('file_path', 'File Path'),
            $DA('expiry_date', 'Expiry Date'),
        ],
    ],

    /* =================================================================
     | Accounting + Payment Gateways
     *================================================================ */
    'accounting-categories' => [
        'class' => 'AccountingCategoryController',
        'model' => 'AccountingCategory',
        'singular' => 'Accounting Category',
        'plural' => 'Accounting Categories',
        'searchable' => ['category_code', 'name'],
        'columns' => [
            'id' => '#',
            'category_code' => 'Code',
            'name' => 'Name',
            'category_type' => 'Type',
            'status' => 'Status',
        ],
        'fields' => [
            $T('category_code', 'Code', true),
            $T('name', 'Name', true),
            $S('category_type', 'Type', "['income' => 'Income', 'expense' => 'Expense']"),
            $TX('description', 'Description'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'accounting-transactions' => [
        'class' => 'AccountingTransactionController',
        'model' => 'AccountingTransaction',
        'singular' => 'Accounting Transaction',
        'plural' => 'Accounting Transactions',
        'with' => ['category'],
        'searchable' => ['transaction_no'],
        'columns' => [
            'id' => '#',
            'transaction_no' => 'No.',
            'transaction_type' => 'Type',
            'category.name' => 'Category',
            'amount' => 'Amount',
            'transaction_date' => 'Date',
            'status' => 'Status',
        ],
        'fields' => [
            $T('transaction_no', 'No.', true),
            $S('accounting_category_id', 'Category', 'AccountingCategory', true),
            $S('transaction_type', 'Type', "['income' => 'Income', 'expense' => 'Expense']"),
            $DA('transaction_date', 'Date'),
            $TX('description', 'Description'),
            $D('amount', 'Amount'),
            $T('payment_method', 'Payment Method'),
            $T('reference_type', 'Reference Type'),
            $N('reference_id', 'Reference ID'),
            $T('attachment_path', 'Attachment'),
            $S('status', 'Status', "['pending' => 'Pending', 'approved' => 'Approved', 'cancelled' => 'Cancelled']"),
        ],
    ],

    'payment-gateways' => [
        'class' => 'PaymentGatewayController',
        'model' => 'PaymentGateway',
        'singular' => 'Payment Gateway',
        'plural' => 'Payment Gateways',
        'searchable' => ['gateway_code', 'gateway_name'],
        'columns' => [
            'id' => '#',
            'gateway_code' => 'Code',
            'gateway_name' => 'Name',
            'provider' => 'Provider',
            'sandbox_mode' => 'Sandbox',
            'status' => 'Status',
        ],
        'fields' => [
            $T('gateway_code', 'Code', true),
            $T('gateway_name', 'Name', true),
            $S('provider', 'Provider', "['aba' => 'ABA Pay', 'wing' => 'Wing', 'pipay' => 'Pipay', 'bakong' => 'Bakong', 'stripe' => 'Stripe', 'other' => 'Other']"),
            $TX('configuration', 'Configuration (JSON)', false, 5),
            $CB('sandbox_mode', 'Sandbox'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    /* =================================================================
     | Sales / Marketing
     *================================================================ */
    'leads' => [
        'class' => 'LeadController',
        'model' => 'Lead',
        'singular' => 'Lead',
        'plural' => 'Leads',
        'searchable' => ['lead_no', 'name', 'phone'],
        'columns' => [
            'id' => '#',
            'lead_no' => 'No.',
            'name' => 'Name',
            'phone' => 'Phone',
            'source' => 'Source',
            'status' => 'Status',
        ],
        'fields' => [
            $T('lead_no', 'No.', true),
            $T('name', 'Name', true),
            $T('phone', 'Phone'),
            $EM('email', 'Email'),
            $S('source', 'Source', "['walk_in' => 'Walk-in', 'website' => 'Website', 'referral' => 'Referral', 'agent' => 'Agent', 'social_media' => 'Social Media', 'other' => 'Other']"),
            $S('room_id', 'Interested Room', 'Room'),
            $DA('appointment_date', 'Appointment'),
            $TX('interest_notes', 'Interest Notes'),
            $S('status', 'Status', "['new' => 'New', 'contacted' => 'Contacted', 'converted' => 'Converted', 'lost' => 'Lost']"),
        ],
    ],

    /* =================================================================
     | ISO QMS
     *================================================================ */
    'controlled-documents' => [
        'class' => 'ControlledDocumentController',
        'model' => 'ControlledDocument',
        'singular' => 'Controlled Document',
        'plural' => 'Controlled Documents',
        'searchable' => ['document_code', 'title'],
        'columns' => [
            'id' => '#',
            'document_code' => 'Code',
            'document_type' => 'Type',
            'title' => 'Title',
            'version_number' => 'Version',
            'status' => 'Status',
        ],
        'fields' => [
            $T('document_code', 'Code', true),
            $S('document_type', 'Type', "['policy' => 'Policy', 'procedure' => 'Procedure', 'form' => 'Form', 'manual' => 'Manual', 'other' => 'Other']"),
            $T('title', 'Title', true),
            $T('version_number', 'Version'),
            $DA('effective_date', 'Effective Date'),
            $T('prepared_by', 'Prepared By'),
            $T('reviewed_by', 'Reviewed By'),
            $T('approved_by', 'Approved By'),
            $DT('approved_at', 'Approved At'),
            $T('file_path', 'File Path'),
            $S('status', 'Status', "['draft' => 'Draft', 'active' => 'Active', 'obsolete' => 'Obsolete']"),
        ],
    ],

    'record-controls' => [
        'class' => 'RecordControlController',
        'model' => 'RecordControl',
        'singular' => 'Record Control',
        'plural' => 'Record Controls',
        'searchable' => ['record_code', 'record_type'],
        'columns' => [
            'id' => '#',
            'record_code' => 'Code',
            'record_type' => 'Type',
            'storage_location' => 'Location',
            'retention_period' => 'Retention',
            'status' => 'Status',
        ],
        'fields' => [
            $T('record_code', 'Code', true),
            $T('record_type', 'Type'),
            $T('storage_location', 'Storage Location'),
            $T('retention_period', 'Retention Period'),
            $N('responsible_person_id', 'Responsible Person ID'),
            $T('disposal_method', 'Disposal Method'),
            $DA('disposal_due_date', 'Disposal Due Date'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'complaints' => [
        'class' => 'ComplaintController',
        'model' => 'Complaint',
        'singular' => 'Complaint',
        'plural' => 'Complaints',
        'with' => ['tenant', 'room'],
        'searchable' => ['complaint_no', 'complaint_type'],
        'columns' => [
            'id' => '#',
            'complaint_no' => 'No.',
            'tenant.full_name' => 'Tenant',
            'room.room_code' => 'Room',
            'complaint_type' => 'Type',
            'received_date' => 'Date',
            'status' => 'Status',
        ],
        'fields' => [
            $T('complaint_no', 'No.', true),
            $S('tenant_id', 'Tenant', 'Tenant'),
            $S('room_id', 'Room', 'Room'),
            $S('responsible_staff_id', 'Responsible Staff', 'Staff'),
            $T('complaint_type', 'Type'),
            $TX('description', 'Description'),
            $DA('received_date', 'Received Date'),
            $DA('resolved_date', 'Resolved Date'),
            $S('status', 'Status', "['open' => 'Open', 'in_progress' => 'In Progress', 'resolved' => 'Resolved', 'closed' => 'Closed']"),
        ],
    ],

    'capa-actions' => [
        'class' => 'CapaActionController',
        'model' => 'CapaAction',
        'singular' => 'CAPA Action',
        'plural' => 'CAPA Actions',
        'searchable' => ['capa_no'],
        'columns' => [
            'id' => '#',
            'capa_no' => 'No.',
            'due_date' => 'Due',
            'verified_date' => 'Verified',
            'status' => 'Status',
        ],
        'fields' => [
            $T('capa_no', 'No.', true),
            $S('complaint_id', 'Complaint', 'Complaint'),
            $S('responsible_staff_id', 'Responsible Staff', 'Staff'),
            $TX('root_cause', 'Root Cause'),
            $TX('corrective_action', 'Corrective Action'),
            $TX('preventive_action', 'Preventive Action'),
            $DA('due_date', 'Due Date'),
            $TX('verification_of_effectiveness', 'Verification'),
            $DA('verified_date', 'Verified Date'),
            $S('status', 'Status', "['open' => 'Open', 'in_progress' => 'In Progress', 'completed' => 'Completed', 'verified' => 'Verified']"),
        ],
    ],

    'feedback' => [
        'class' => 'FeedbackController',
        'model' => 'Feedback',
        'singular' => 'Feedback',
        'plural' => 'Feedback',
        'with' => ['tenant', 'room'],
        'searchable' => [],
        'columns' => [
            'id' => '#',
            'tenant_id' => 'Tenant',
            'room_id' => 'Room',
            'rating' => 'Rating',
            'overall_satisfaction_score' => 'Overall',
            'feedback_date' => 'Date',
            'status' => 'Status',
        ],
        'fields' => [
            $S('tenant_id', 'Tenant', 'Tenant'),
            $S('room_id', 'Room', 'Room'),
            $N('rating', 'Rating (1-5)'),
            $TX('comment', 'Comment'),
            $N('service_quality_score', 'Service Quality (1-5)'),
            $N('cleanliness_score', 'Cleanliness (1-5)'),
            $N('security_score', 'Security (1-5)'),
            $N('overall_satisfaction_score', 'Overall (1-5)'),
            $DA('feedback_date', 'Date'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    /* =================================================================
     | Notifications + Reports
     *================================================================ */
    'notification-templates' => [
        'class' => 'NotificationTemplateController',
        'model' => 'NotificationTemplate',
        'singular' => 'Notification Template',
        'plural' => 'Notification Templates',
        'searchable' => ['template_code', 'subject'],
        'columns' => [
            'id' => '#',
            'template_code' => 'Code',
            'template_type' => 'Type',
            'channel' => 'Channel',
            'subject' => 'Subject',
            'status' => 'Status',
        ],
        'fields' => [
            $T('template_code', 'Code', true),
            $T('template_type', 'Type'),
            $S('channel', 'Channel', "['email' => 'Email', 'sms' => 'SMS', 'in_app' => 'In-app', 'push' => 'Push']"),
            $T('subject', 'Subject'),
            $TX('body', 'Body', false, 6),
            $TX('variables', 'Variables (JSON)', false, 3),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'notifications' => [
        'class' => 'NotificationController',
        'model' => 'AppNotification',
        'singular' => 'Notification',
        'plural' => 'Notifications',
        'searchable' => ['notification_no', 'recipient', 'subject'],
        'columns' => [
            'id' => '#',
            'notification_no' => 'No.',
            'channel' => 'Channel',
            'recipient' => 'Recipient',
            'subject' => 'Subject',
            'status' => 'Status',
        ],
        'fields' => [
            $T('notification_no', 'No.', true),
            $S('template_id', 'Template', 'NotificationTemplate'),
            $S('tenant_id', 'Tenant', 'Tenant'),
            $S('user_id', 'User', 'SystemUser'),
            $S('channel', 'Channel', "['email' => 'Email', 'sms' => 'SMS', 'in_app' => 'In-app', 'push' => 'Push']"),
            $T('notification_type', 'Type'),
            $T('recipient', 'Recipient'),
            $T('subject', 'Subject'),
            $TX('message', 'Message', false, 4),
            $DT('scheduled_at', 'Scheduled At'),
            $DT('sent_at', 'Sent At'),
            $S('status', 'Status', "['scheduled' => 'Scheduled', 'sent' => 'Sent', 'failed' => 'Failed', 'read' => 'Read']"),
        ],
    ],

    'report-exports' => [
        'class' => 'ReportExportController',
        'model' => 'ReportExport',
        'singular' => 'Report Export',
        'plural' => 'Report Exports',
        'searchable' => ['export_no', 'report_type'],
        'columns' => [
            'id' => '#',
            'export_no' => 'No.',
            'report_type' => 'Type',
            'format' => 'Format',
            'requested_at' => 'Requested',
            'status' => 'Status',
        ],
        'fields' => [
            $T('export_no', 'No.', true),
            $T('report_type', 'Report Type'),
            $TX('filters', 'Filters (JSON)'),
            $S('format', 'Format', "['pdf' => 'PDF', 'excel' => 'Excel', 'csv' => 'CSV']"),
            $T('file_path', 'File Path'),
            $T('requested_by', 'Requested By'),
            $DT('requested_at', 'Requested At'),
            $DT('completed_at', 'Completed At'),
            $S('status', 'Status', "['queued' => 'Queued', 'processing' => 'Processing', 'completed' => 'Completed', 'failed' => 'Failed']"),
        ],
    ],

    /* =================================================================
     | RBAC + System
     *================================================================ */
    'system-roles' => [
        'class' => 'SystemRoleController',
        'model' => 'SystemRole',
        'singular' => 'Role',
        'plural' => 'Roles',
        'searchable' => ['role_code', 'name'],
        'columns' => [
            'id' => '#',
            'role_code' => 'Code',
            'name' => 'Name',
            'description' => 'Description',
            'status' => 'Status',
        ],
        'fields' => [
            $T('role_code', 'Code', true),
            $T('name', 'Name', true),
            $TX('description', 'Description'),
            $CB('is_system', 'System Role'),
            $S('status', 'Status', '@status_default'),
        ],
    ],

    'system-permissions' => [
        'class' => 'SystemPermissionController',
        'model' => 'SystemPermission',
        'singular' => 'Permission',
        'plural' => 'Permissions',
        'searchable' => ['permission_code', 'module', 'action'],
        'columns' => [
            'id' => '#',
            'permission_code' => 'Code',
            'module' => 'Module',
            'action' => 'Action',
            'name' => 'Name',
        ],
        'fields' => [
            $T('permission_code', 'Code', true),
            $T('module', 'Module', true),
            $T('action', 'Action', true),
            $T('name', 'Name', true),
            $TX('description', 'Description'),
        ],
    ],

    'system-users' => [
        'class' => 'SystemUserController',
        'model' => 'SystemUser',
        'singular' => 'User',
        'plural' => 'Users',
        'searchable' => ['username', 'email', 'name'],
        'columns' => [
            'id' => '#',
            'name' => 'Name',
            'username' => 'Username',
            'email' => 'Email',
            'user_type' => 'Type',
            'status' => 'Status',
        ],
        'fields' => [
            $T('name', 'Name', true),
            $T('username', 'Username', true),
            $EM('email', 'Email', true),
            $T('phone', 'Phone'),
            $S('user_type', 'User Type', "['admin' => 'Admin', 'staff' => 'Staff', 'tenant' => 'Tenant']"),
            $PW('password', 'Password (leave blank to keep)'),
            $S('staff_id', 'Linked Staff', 'Staff'),
            $S('tenant_id', 'Linked Tenant', 'Tenant'),
            $CB('two_factor_enabled', '2FA Enabled'),
            $S('status', 'Status', "['active' => 'Active', 'inactive' => 'Inactive', 'locked' => 'Locked']"),
        ],
        'extra_rules' => [
            'password' => "['nullable', 'string', 'min:6']",
        ],
        'before_save' => '$password = $request->input("password"); if (! $password) { unset($data["password"]); } else { $data["password"] = bcrypt($password); }',
    ],

    'system-settings' => [
        'class' => 'SystemSettingController',
        'model' => 'SystemSetting',
        'singular' => 'System Setting',
        'plural' => 'System Settings',
        'searchable' => ['setting_group', 'setting_key'],
        'columns' => [
            'id' => '#',
            'setting_group' => 'Group',
            'setting_key' => 'Key',
            'setting_value' => 'Value',
            'value_type' => 'Type',
        ],
        'fields' => [
            $T('setting_group', 'Group', true),
            $T('setting_key', 'Key', true),
            $TX('setting_value', 'Value'),
            $S('value_type', 'Value Type', "['string' => 'String', 'integer' => 'Integer', 'boolean' => 'Boolean', 'json' => 'JSON']"),
            $CB('is_encrypted', 'Encrypted'),
            $TX('description', 'Description'),
        ],
    ],

    'audit-logs' => [
        'class' => 'AuditLogController',
        'model' => 'AuditLog',
        'singular' => 'Audit Log',
        'plural' => 'Audit Logs',
        'read_only' => true,
        'searchable' => ['module', 'action'],
        'columns' => [
            'id' => '#',
            'user_id' => 'User',
            'module' => 'Module',
            'action' => 'Action',
            'auditable_type' => 'Auditable',
            'auditable_id' => 'ID',
            'performed_at' => 'When',
        ],
        'fields' => [],
    ],

    'backup-logs' => [
        'class' => 'BackupLogController',
        'model' => 'BackupLog',
        'singular' => 'Backup Log',
        'plural' => 'Backup Logs',
        'searchable' => ['backup_no', 'backup_type'],
        'columns' => [
            'id' => '#',
            'backup_no' => 'No.',
            'backup_type' => 'Type',
            'storage_location' => 'Location',
            'started_at' => 'Started',
            'completed_at' => 'Completed',
            'status' => 'Status',
        ],
        'fields' => [
            $T('backup_no', 'No.', true),
            $S('backup_type', 'Type', "['full' => 'Full', 'incremental' => 'Incremental', 'manual' => 'Manual']"),
            $T('storage_location', 'Storage Location'),
            $T('file_path', 'File Path'),
            $N('file_size_bytes', 'File Size (bytes)'),
            $DT('started_at', 'Started At'),
            $DT('completed_at', 'Completed At'),
            $DT('restore_tested_at', 'Restore Tested At'),
            $S('status', 'Status', "['running' => 'Running', 'completed' => 'Completed', 'failed' => 'Failed']"),
            $TX('error_message', 'Error Message'),
        ],
    ],

    'media-files' => [
        'class' => 'MediaFileController',
        'model' => 'MediaFile',
        'singular' => 'Media File',
        'plural' => 'Media Files',
        'searchable' => ['original_name', 'collection'],
        'columns' => [
            'id' => '#',
            'original_name' => 'Name',
            'collection' => 'Collection',
            'fileable_type' => 'Owner Type',
            'fileable_id' => 'Owner ID',
            'mime_type' => 'MIME',
            'size_bytes' => 'Size',
        ],
        'fields' => [
            $T('original_name', 'Original Name', true),
            $T('file_name', 'File Name'),
            $T('collection', 'Collection'),
            $T('fileable_type', 'Owner Type'),
            $N('fileable_id', 'Owner ID'),
            $T('mime_type', 'MIME Type'),
            $T('disk', 'Disk'),
            $T('path', 'Path'),
            $N('size_bytes', 'Size (bytes)'),
            $T('uploaded_by', 'Uploaded By'),
        ],
    ],
];
